/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiShiftsRouteImport } from './routes/api/shifts'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiBoardsRouteImport } from './routes/api/boards'
import { Route as ApiShiftsMineRouteImport } from './routes/api/shifts/mine'
import { Route as ApiShiftsIdRouteImport } from './routes/api/shifts/$id'
import { Route as ApiEventsIdRouteImport } from './routes/api/events/$id'
import { Route as ApiCritterProfileRouteImport } from './routes/api/critter/profile'
import { Route as ApiBoardsSlugRouteImport } from './routes/api/boards/$slug'
import { Route as ApiAssignmentsQueueRouteImport } from './routes/api/assignments/queue'
import { Route as ApiShiftsIdRequestRouteImport } from './routes/api/shifts/$id/request'
import { Route as ApiShiftsIdPublishRouteImport } from './routes/api/shifts/$id/publish'
import { Route as ApiEventsIdPublishRouteImport } from './routes/api/events/$id/publish'
import { Route as ApiEventsIdArchiveRouteImport } from './routes/api/events/$id/archive'
import { Route as ApiAssignmentsIdWithdrawRouteImport } from './routes/api/assignments/$id/withdraw'
import { Route as ApiAssignmentsIdDeclineRouteImport } from './routes/api/assignments/$id/decline'
import { Route as ApiAssignmentsIdApproveRouteImport } from './routes/api/assignments/$id/approve'
import { Route as ApiBoardsSlugColumnsIndexRouteImport } from './routes/api/boards/$slug/columns/index'
import { Route as ApiBoardsSlugColumnsReorderRouteImport } from './routes/api/boards/$slug/columns/reorder'
import { Route as ApiBoardsSlugColumnsIdRouteImport } from './routes/api/boards/$slug/columns/$id'
import { Route as ApiBoardsSlugCardsIdRouteImport } from './routes/api/boards/$slug/cards/$id'
import { Route as ApiBoardsSlugCardsIdCommentsRouteImport } from './routes/api/boards/$slug/cards/$id/comments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShiftsRoute = ApiShiftsRouteImport.update({
  id: '/api/shifts',
  path: '/api/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsRoute = ApiBoardsRouteImport.update({
  id: '/api/boards',
  path: '/api/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShiftsMineRoute = ApiShiftsMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => ApiShiftsRoute,
} as any)
const ApiShiftsIdRoute = ApiShiftsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiShiftsRoute,
} as any)
const ApiEventsIdRoute = ApiEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEventsRoute,
} as any)
const ApiCritterProfileRoute = ApiCritterProfileRouteImport.update({
  id: '/api/critter/profile',
  path: '/api/critter/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsSlugRoute = ApiBoardsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBoardsRoute,
} as any)
const ApiAssignmentsQueueRoute = ApiAssignmentsQueueRouteImport.update({
  id: '/api/assignments/queue',
  path: '/api/assignments/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShiftsIdRequestRoute = ApiShiftsIdRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => ApiShiftsIdRoute,
} as any)
const ApiShiftsIdPublishRoute = ApiShiftsIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => ApiShiftsIdRoute,
} as any)
const ApiEventsIdPublishRoute = ApiEventsIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => ApiEventsIdRoute,
} as any)
const ApiEventsIdArchiveRoute = ApiEventsIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiEventsIdRoute,
} as any)
const ApiAssignmentsIdWithdrawRoute =
  ApiAssignmentsIdWithdrawRouteImport.update({
    id: '/api/assignments/$id/withdraw',
    path: '/api/assignments/$id/withdraw',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAssignmentsIdDeclineRoute = ApiAssignmentsIdDeclineRouteImport.update({
  id: '/api/assignments/$id/decline',
  path: '/api/assignments/$id/decline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssignmentsIdApproveRoute = ApiAssignmentsIdApproveRouteImport.update({
  id: '/api/assignments/$id/approve',
  path: '/api/assignments/$id/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsSlugColumnsIndexRoute =
  ApiBoardsSlugColumnsIndexRouteImport.update({
    id: '/columns/',
    path: '/columns/',
    getParentRoute: () => ApiBoardsSlugRoute,
  } as any)
const ApiBoardsSlugColumnsReorderRoute =
  ApiBoardsSlugColumnsReorderRouteImport.update({
    id: '/columns/reorder',
    path: '/columns/reorder',
    getParentRoute: () => ApiBoardsSlugRoute,
  } as any)
const ApiBoardsSlugColumnsIdRoute = ApiBoardsSlugColumnsIdRouteImport.update({
  id: '/columns/$id',
  path: '/columns/$id',
  getParentRoute: () => ApiBoardsSlugRoute,
} as any)
const ApiBoardsSlugCardsIdRoute = ApiBoardsSlugCardsIdRouteImport.update({
  id: '/cards/$id',
  path: '/cards/$id',
  getParentRoute: () => ApiBoardsSlugRoute,
} as any)
const ApiBoardsSlugCardsIdCommentsRoute =
  ApiBoardsSlugCardsIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => ApiBoardsSlugCardsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/boards': typeof ApiBoardsRouteWithChildren
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/shifts': typeof ApiShiftsRouteWithChildren
  '/api/assignments/queue': typeof ApiAssignmentsQueueRoute
  '/api/boards/$slug': typeof ApiBoardsSlugRouteWithChildren
  '/api/critter/profile': typeof ApiCritterProfileRoute
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/shifts/$id': typeof ApiShiftsIdRouteWithChildren
  '/api/shifts/mine': typeof ApiShiftsMineRoute
  '/api/assignments/$id/approve': typeof ApiAssignmentsIdApproveRoute
  '/api/assignments/$id/decline': typeof ApiAssignmentsIdDeclineRoute
  '/api/assignments/$id/withdraw': typeof ApiAssignmentsIdWithdrawRoute
  '/api/events/$id/archive': typeof ApiEventsIdArchiveRoute
  '/api/events/$id/publish': typeof ApiEventsIdPublishRoute
  '/api/shifts/$id/publish': typeof ApiShiftsIdPublishRoute
  '/api/shifts/$id/request': typeof ApiShiftsIdRequestRoute
  '/api/boards/$slug/cards/$id': typeof ApiBoardsSlugCardsIdRouteWithChildren
  '/api/boards/$slug/columns/$id': typeof ApiBoardsSlugColumnsIdRoute
  '/api/boards/$slug/columns/reorder': typeof ApiBoardsSlugColumnsReorderRoute
  '/api/boards/$slug/columns/': typeof ApiBoardsSlugColumnsIndexRoute
  '/api/boards/$slug/cards/$id/comments': typeof ApiBoardsSlugCardsIdCommentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/boards': typeof ApiBoardsRouteWithChildren
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/shifts': typeof ApiShiftsRouteWithChildren
  '/api/assignments/queue': typeof ApiAssignmentsQueueRoute
  '/api/boards/$slug': typeof ApiBoardsSlugRouteWithChildren
  '/api/critter/profile': typeof ApiCritterProfileRoute
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/shifts/$id': typeof ApiShiftsIdRouteWithChildren
  '/api/shifts/mine': typeof ApiShiftsMineRoute
  '/api/assignments/$id/approve': typeof ApiAssignmentsIdApproveRoute
  '/api/assignments/$id/decline': typeof ApiAssignmentsIdDeclineRoute
  '/api/assignments/$id/withdraw': typeof ApiAssignmentsIdWithdrawRoute
  '/api/events/$id/archive': typeof ApiEventsIdArchiveRoute
  '/api/events/$id/publish': typeof ApiEventsIdPublishRoute
  '/api/shifts/$id/publish': typeof ApiShiftsIdPublishRoute
  '/api/shifts/$id/request': typeof ApiShiftsIdRequestRoute
  '/api/boards/$slug/cards/$id': typeof ApiBoardsSlugCardsIdRouteWithChildren
  '/api/boards/$slug/columns/$id': typeof ApiBoardsSlugColumnsIdRoute
  '/api/boards/$slug/columns/reorder': typeof ApiBoardsSlugColumnsReorderRoute
  '/api/boards/$slug/columns': typeof ApiBoardsSlugColumnsIndexRoute
  '/api/boards/$slug/cards/$id/comments': typeof ApiBoardsSlugCardsIdCommentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/boards': typeof ApiBoardsRouteWithChildren
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/shifts': typeof ApiShiftsRouteWithChildren
  '/api/assignments/queue': typeof ApiAssignmentsQueueRoute
  '/api/boards/$slug': typeof ApiBoardsSlugRouteWithChildren
  '/api/critter/profile': typeof ApiCritterProfileRoute
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/shifts/$id': typeof ApiShiftsIdRouteWithChildren
  '/api/shifts/mine': typeof ApiShiftsMineRoute
  '/api/assignments/$id/approve': typeof ApiAssignmentsIdApproveRoute
  '/api/assignments/$id/decline': typeof ApiAssignmentsIdDeclineRoute
  '/api/assignments/$id/withdraw': typeof ApiAssignmentsIdWithdrawRoute
  '/api/events/$id/archive': typeof ApiEventsIdArchiveRoute
  '/api/events/$id/publish': typeof ApiEventsIdPublishRoute
  '/api/shifts/$id/publish': typeof ApiShiftsIdPublishRoute
  '/api/shifts/$id/request': typeof ApiShiftsIdRequestRoute
  '/api/boards/$slug/cards/$id': typeof ApiBoardsSlugCardsIdRouteWithChildren
  '/api/boards/$slug/columns/$id': typeof ApiBoardsSlugColumnsIdRoute
  '/api/boards/$slug/columns/reorder': typeof ApiBoardsSlugColumnsReorderRoute
  '/api/boards/$slug/columns/': typeof ApiBoardsSlugColumnsIndexRoute
  '/api/boards/$slug/cards/$id/comments': typeof ApiBoardsSlugCardsIdCommentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/boards'
    | '/api/events'
    | '/api/health'
    | '/api/shifts'
    | '/api/assignments/queue'
    | '/api/boards/$slug'
    | '/api/critter/profile'
    | '/api/events/$id'
    | '/api/shifts/$id'
    | '/api/shifts/mine'
    | '/api/assignments/$id/approve'
    | '/api/assignments/$id/decline'
    | '/api/assignments/$id/withdraw'
    | '/api/events/$id/archive'
    | '/api/events/$id/publish'
    | '/api/shifts/$id/publish'
    | '/api/shifts/$id/request'
    | '/api/boards/$slug/cards/$id'
    | '/api/boards/$slug/columns/$id'
    | '/api/boards/$slug/columns/reorder'
    | '/api/boards/$slug/columns/'
    | '/api/boards/$slug/cards/$id/comments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/boards'
    | '/api/events'
    | '/api/health'
    | '/api/shifts'
    | '/api/assignments/queue'
    | '/api/boards/$slug'
    | '/api/critter/profile'
    | '/api/events/$id'
    | '/api/shifts/$id'
    | '/api/shifts/mine'
    | '/api/assignments/$id/approve'
    | '/api/assignments/$id/decline'
    | '/api/assignments/$id/withdraw'
    | '/api/events/$id/archive'
    | '/api/events/$id/publish'
    | '/api/shifts/$id/publish'
    | '/api/shifts/$id/request'
    | '/api/boards/$slug/cards/$id'
    | '/api/boards/$slug/columns/$id'
    | '/api/boards/$slug/columns/reorder'
    | '/api/boards/$slug/columns'
    | '/api/boards/$slug/cards/$id/comments'
  id:
    | '__root__'
    | '/'
    | '/api/boards'
    | '/api/events'
    | '/api/health'
    | '/api/shifts'
    | '/api/assignments/queue'
    | '/api/boards/$slug'
    | '/api/critter/profile'
    | '/api/events/$id'
    | '/api/shifts/$id'
    | '/api/shifts/mine'
    | '/api/assignments/$id/approve'
    | '/api/assignments/$id/decline'
    | '/api/assignments/$id/withdraw'
    | '/api/events/$id/archive'
    | '/api/events/$id/publish'
    | '/api/shifts/$id/publish'
    | '/api/shifts/$id/request'
    | '/api/boards/$slug/cards/$id'
    | '/api/boards/$slug/columns/$id'
    | '/api/boards/$slug/columns/reorder'
    | '/api/boards/$slug/columns/'
    | '/api/boards/$slug/cards/$id/comments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBoardsRoute: typeof ApiBoardsRouteWithChildren
  ApiEventsRoute: typeof ApiEventsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiShiftsRoute: typeof ApiShiftsRouteWithChildren
  ApiAssignmentsQueueRoute: typeof ApiAssignmentsQueueRoute
  ApiCritterProfileRoute: typeof ApiCritterProfileRoute
  ApiAssignmentsIdApproveRoute: typeof ApiAssignmentsIdApproveRoute
  ApiAssignmentsIdDeclineRoute: typeof ApiAssignmentsIdDeclineRoute
  ApiAssignmentsIdWithdrawRoute: typeof ApiAssignmentsIdWithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shifts': {
      id: '/api/shifts'
      path: '/api/shifts'
      fullPath: '/api/shifts'
      preLoaderRoute: typeof ApiShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards': {
      id: '/api/boards'
      path: '/api/boards'
      fullPath: '/api/boards'
      preLoaderRoute: typeof ApiBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shifts/mine': {
      id: '/api/shifts/mine'
      path: '/mine'
      fullPath: '/api/shifts/mine'
      preLoaderRoute: typeof ApiShiftsMineRouteImport
      parentRoute: typeof ApiShiftsRoute
    }
    '/api/shifts/$id': {
      id: '/api/shifts/$id'
      path: '/$id'
      fullPath: '/api/shifts/$id'
      preLoaderRoute: typeof ApiShiftsIdRouteImport
      parentRoute: typeof ApiShiftsRoute
    }
    '/api/events/$id': {
      id: '/api/events/$id'
      path: '/$id'
      fullPath: '/api/events/$id'
      preLoaderRoute: typeof ApiEventsIdRouteImport
      parentRoute: typeof ApiEventsRoute
    }
    '/api/critter/profile': {
      id: '/api/critter/profile'
      path: '/api/critter/profile'
      fullPath: '/api/critter/profile'
      preLoaderRoute: typeof ApiCritterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards/$slug': {
      id: '/api/boards/$slug'
      path: '/$slug'
      fullPath: '/api/boards/$slug'
      preLoaderRoute: typeof ApiBoardsSlugRouteImport
      parentRoute: typeof ApiBoardsRoute
    }
    '/api/assignments/queue': {
      id: '/api/assignments/queue'
      path: '/api/assignments/queue'
      fullPath: '/api/assignments/queue'
      preLoaderRoute: typeof ApiAssignmentsQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shifts/$id/request': {
      id: '/api/shifts/$id/request'
      path: '/request'
      fullPath: '/api/shifts/$id/request'
      preLoaderRoute: typeof ApiShiftsIdRequestRouteImport
      parentRoute: typeof ApiShiftsIdRoute
    }
    '/api/shifts/$id/publish': {
      id: '/api/shifts/$id/publish'
      path: '/publish'
      fullPath: '/api/shifts/$id/publish'
      preLoaderRoute: typeof ApiShiftsIdPublishRouteImport
      parentRoute: typeof ApiShiftsIdRoute
    }
    '/api/events/$id/publish': {
      id: '/api/events/$id/publish'
      path: '/publish'
      fullPath: '/api/events/$id/publish'
      preLoaderRoute: typeof ApiEventsIdPublishRouteImport
      parentRoute: typeof ApiEventsIdRoute
    }
    '/api/events/$id/archive': {
      id: '/api/events/$id/archive'
      path: '/archive'
      fullPath: '/api/events/$id/archive'
      preLoaderRoute: typeof ApiEventsIdArchiveRouteImport
      parentRoute: typeof ApiEventsIdRoute
    }
    '/api/assignments/$id/withdraw': {
      id: '/api/assignments/$id/withdraw'
      path: '/api/assignments/$id/withdraw'
      fullPath: '/api/assignments/$id/withdraw'
      preLoaderRoute: typeof ApiAssignmentsIdWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assignments/$id/decline': {
      id: '/api/assignments/$id/decline'
      path: '/api/assignments/$id/decline'
      fullPath: '/api/assignments/$id/decline'
      preLoaderRoute: typeof ApiAssignmentsIdDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assignments/$id/approve': {
      id: '/api/assignments/$id/approve'
      path: '/api/assignments/$id/approve'
      fullPath: '/api/assignments/$id/approve'
      preLoaderRoute: typeof ApiAssignmentsIdApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards/$slug/columns/': {
      id: '/api/boards/$slug/columns/'
      path: '/columns'
      fullPath: '/api/boards/$slug/columns/'
      preLoaderRoute: typeof ApiBoardsSlugColumnsIndexRouteImport
      parentRoute: typeof ApiBoardsSlugRoute
    }
    '/api/boards/$slug/columns/reorder': {
      id: '/api/boards/$slug/columns/reorder'
      path: '/columns/reorder'
      fullPath: '/api/boards/$slug/columns/reorder'
      preLoaderRoute: typeof ApiBoardsSlugColumnsReorderRouteImport
      parentRoute: typeof ApiBoardsSlugRoute
    }
    '/api/boards/$slug/columns/$id': {
      id: '/api/boards/$slug/columns/$id'
      path: '/columns/$id'
      fullPath: '/api/boards/$slug/columns/$id'
      preLoaderRoute: typeof ApiBoardsSlugColumnsIdRouteImport
      parentRoute: typeof ApiBoardsSlugRoute
    }
    '/api/boards/$slug/cards/$id': {
      id: '/api/boards/$slug/cards/$id'
      path: '/cards/$id'
      fullPath: '/api/boards/$slug/cards/$id'
      preLoaderRoute: typeof ApiBoardsSlugCardsIdRouteImport
      parentRoute: typeof ApiBoardsSlugRoute
    }
    '/api/boards/$slug/cards/$id/comments': {
      id: '/api/boards/$slug/cards/$id/comments'
      path: '/comments'
      fullPath: '/api/boards/$slug/cards/$id/comments'
      preLoaderRoute: typeof ApiBoardsSlugCardsIdCommentsRouteImport
      parentRoute: typeof ApiBoardsSlugCardsIdRoute
    }
  }
}

interface ApiBoardsSlugCardsIdRouteChildren {
  ApiBoardsSlugCardsIdCommentsRoute: typeof ApiBoardsSlugCardsIdCommentsRoute
}

const ApiBoardsSlugCardsIdRouteChildren: ApiBoardsSlugCardsIdRouteChildren = {
  ApiBoardsSlugCardsIdCommentsRoute: ApiBoardsSlugCardsIdCommentsRoute,
}

const ApiBoardsSlugCardsIdRouteWithChildren =
  ApiBoardsSlugCardsIdRoute._addFileChildren(ApiBoardsSlugCardsIdRouteChildren)

interface ApiBoardsSlugRouteChildren {
  ApiBoardsSlugCardsIdRoute: typeof ApiBoardsSlugCardsIdRouteWithChildren
  ApiBoardsSlugColumnsIdRoute: typeof ApiBoardsSlugColumnsIdRoute
  ApiBoardsSlugColumnsReorderRoute: typeof ApiBoardsSlugColumnsReorderRoute
  ApiBoardsSlugColumnsIndexRoute: typeof ApiBoardsSlugColumnsIndexRoute
}

const ApiBoardsSlugRouteChildren: ApiBoardsSlugRouteChildren = {
  ApiBoardsSlugCardsIdRoute: ApiBoardsSlugCardsIdRouteWithChildren,
  ApiBoardsSlugColumnsIdRoute: ApiBoardsSlugColumnsIdRoute,
  ApiBoardsSlugColumnsReorderRoute: ApiBoardsSlugColumnsReorderRoute,
  ApiBoardsSlugColumnsIndexRoute: ApiBoardsSlugColumnsIndexRoute,
}

const ApiBoardsSlugRouteWithChildren = ApiBoardsSlugRoute._addFileChildren(
  ApiBoardsSlugRouteChildren,
)

interface ApiBoardsRouteChildren {
  ApiBoardsSlugRoute: typeof ApiBoardsSlugRouteWithChildren
}

const ApiBoardsRouteChildren: ApiBoardsRouteChildren = {
  ApiBoardsSlugRoute: ApiBoardsSlugRouteWithChildren,
}

const ApiBoardsRouteWithChildren = ApiBoardsRoute._addFileChildren(
  ApiBoardsRouteChildren,
)

interface ApiEventsIdRouteChildren {
  ApiEventsIdArchiveRoute: typeof ApiEventsIdArchiveRoute
  ApiEventsIdPublishRoute: typeof ApiEventsIdPublishRoute
}

const ApiEventsIdRouteChildren: ApiEventsIdRouteChildren = {
  ApiEventsIdArchiveRoute: ApiEventsIdArchiveRoute,
  ApiEventsIdPublishRoute: ApiEventsIdPublishRoute,
}

const ApiEventsIdRouteWithChildren = ApiEventsIdRoute._addFileChildren(
  ApiEventsIdRouteChildren,
)

interface ApiEventsRouteChildren {
  ApiEventsIdRoute: typeof ApiEventsIdRouteWithChildren
}

const ApiEventsRouteChildren: ApiEventsRouteChildren = {
  ApiEventsIdRoute: ApiEventsIdRouteWithChildren,
}

const ApiEventsRouteWithChildren = ApiEventsRoute._addFileChildren(
  ApiEventsRouteChildren,
)

interface ApiShiftsIdRouteChildren {
  ApiShiftsIdPublishRoute: typeof ApiShiftsIdPublishRoute
  ApiShiftsIdRequestRoute: typeof ApiShiftsIdRequestRoute
}

const ApiShiftsIdRouteChildren: ApiShiftsIdRouteChildren = {
  ApiShiftsIdPublishRoute: ApiShiftsIdPublishRoute,
  ApiShiftsIdRequestRoute: ApiShiftsIdRequestRoute,
}

const ApiShiftsIdRouteWithChildren = ApiShiftsIdRoute._addFileChildren(
  ApiShiftsIdRouteChildren,
)

interface ApiShiftsRouteChildren {
  ApiShiftsIdRoute: typeof ApiShiftsIdRouteWithChildren
  ApiShiftsMineRoute: typeof ApiShiftsMineRoute
}

const ApiShiftsRouteChildren: ApiShiftsRouteChildren = {
  ApiShiftsIdRoute: ApiShiftsIdRouteWithChildren,
  ApiShiftsMineRoute: ApiShiftsMineRoute,
}

const ApiShiftsRouteWithChildren = ApiShiftsRoute._addFileChildren(
  ApiShiftsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBoardsRoute: ApiBoardsRouteWithChildren,
  ApiEventsRoute: ApiEventsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiShiftsRoute: ApiShiftsRouteWithChildren,
  ApiAssignmentsQueueRoute: ApiAssignmentsQueueRoute,
  ApiCritterProfileRoute: ApiCritterProfileRoute,
  ApiAssignmentsIdApproveRoute: ApiAssignmentsIdApproveRoute,
  ApiAssignmentsIdDeclineRoute: ApiAssignmentsIdDeclineRoute,
  ApiAssignmentsIdWithdrawRoute: ApiAssignmentsIdWithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
